spring.application.name=JobPortal

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration


# Set Spring framework logging
logging.level.org.springframework=INFO

# Set logging for your project classes
logging.level.com.basharat.JobPortal=DEBUG
